--local Remap = require("pranv.keymap")
--local nnoremap = Remap.nnoremap
--local inoremap = Remap.inoremap
--
--local function config(_config)
--	return vim.tbl_deep_extend("force", {
--		on_attach = function()
--			nnoremap("gd", function() vim.lsp.buf.definition() end)
--			nnoremap("K", function() vim.lsp.buf.hover() end)
--			nnoremap("<leader>vrr", function() vim.lsp.buf.references() end)
--			nnoremap("<leader>vrn", function() vim.lsp.buf.rename() end)
--			inoremap("<C-h>", function() vim.lsp.buf.signature_help() end)
--		end,
--	}, _config or {})
--end
--
--require 'lspconfig'.pyright.setup(config())
--
--require("lspconfig").gopls.setup(config({
--	cmd = { "gopls", "serve" },
--	settings = {
--		gopls = {
--			analyses = {
--				unusedparams = true,
--			},
--			staticcheck = true,
--		},
--	},
--}))
--
--require("lspconfig").rust_analyzer.setup(config({
--	cmd = { "rustup", "run", "nightly", "rust-analyzer" },
--	--[[
--    settings = {
--        rust = {
--            unstable_features = true,
--            build_on_save = false,
--            all_features = true,
--        },
--    }
--    --]]
--}))
