require("pranv.set")
require("pranv.remap")
require("pranv.command")
require("pranv.neogit")
require("pranv.nvim-tree")
require("pranv.lualine")
require("pranv.telescope")
require("pranv.nvim-cmp")
print("hello from pranv")
